-- MySQL Script generated by MySQL Workbench
-- Thu 28 Apr 2016 18:19:25 EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema climmobv3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `climmobv3` ;

-- -----------------------------------------------------
-- Schema climmobv3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `climmobv3` DEFAULT CHARACTER SET utf8 ;
USE `climmobv3` ;

-- -----------------------------------------------------
-- Table `climmobv3`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`country` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`country` (
  `cnty_cod` VARCHAR(3) NOT NULL,
  `cnty_name` VARCHAR(120) NULL,
  PRIMARY KEY (`cnty_cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`sector` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`sector` (
  `sector_cod` INT NOT NULL AUTO_INCREMENT,
  `sector_name` VARCHAR(120) NULL,
  PRIMARY KEY (`sector_cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`user` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`user` (
  `user_name` VARCHAR(80) NOT NULL,
  `user_fullname` VARCHAR(120) NULL,
  `user_password` VARCHAR(80) NULL,
  `user_organization` VARCHAR(120) NULL,
  `user_email` VARCHAR(120) NULL,
  `user_apikey` VARCHAR(45) NULL,
  `user_about` TEXT NULL,
  `user_cnty` VARCHAR(3) NOT NULL,
  `user_sector` INT NOT NULL,
  `user_active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`user_name`),
  INDEX `fk_user_lkpcountry_idx` (`user_cnty` ASC),
  INDEX `fk_user_lkpsector1_idx` (`user_sector` ASC),
  CONSTRAINT `fk_user_lkpcountry`
    FOREIGN KEY (`user_cnty`)
    REFERENCES `climmobv3`.`country` (`cnty_cod`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_lkpsector1`
    FOREIGN KEY (`user_sector`)
    REFERENCES `climmobv3`.`sector` (`sector_cod`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'User table: Store the users';


-- -----------------------------------------------------
-- Table `climmobv3`.`activitylog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`activitylog` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`activitylog` (
  `log_id` INT(9) NOT NULL AUTO_INCREMENT,
  `log_user` VARCHAR(80) NOT NULL,
  `log_datetime` DATETIME NULL,
  `log_type` VARCHAR(3) NULL,
  `log_message` TEXT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_activitylog_user1_idx` (`log_user` ASC),
  CONSTRAINT `fk_activitylog_user1`
    FOREIGN KEY (`log_user`)
    REFERENCES `climmobv3`.`user` (`user_name`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`apilog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`apilog` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`apilog` (
  `log_id` INT(9) NOT NULL AUTO_INCREMENT,
  `log_datetime` DATETIME NULL,
  `log_ip` VARCHAR(45) NULL,
  `log_user` VARCHAR(80) NOT NULL,
  `log_uuid` VARCHAR(80) NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_apilog_user1_idx` (`log_user` ASC),
  CONSTRAINT `fk_apilog_user1`
    FOREIGN KEY (`log_user`)
    REFERENCES `climmobv3`.`user` (`user_name`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`project` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`project` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `project_name` VARCHAR(120) NULL,
  `project_abstract` TEXT NULL,
  `project_tags` TEXT NULL,
  `project_pi` VARCHAR(120) NULL,
  `project_piemail` VARCHAR(120) NULL,
  PRIMARY KEY (`user_name`, `project_cod`),
  INDEX `fk_project_user1_idx` (`user_name` ASC),
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`user_name`)
    REFERENCES `climmobv3`.`user` (`user_name`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`question` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question_desc` VARCHAR(120) NULL,
  `question_notes` TEXT NULL,
  `question_unit` VARCHAR(120) NULL,
  `question_dtype` INT NULL COMMENT 'Can also be Producer input, producer select, package select, enumerator select',
  `question_oth` INT NULL,
  `question_cmp` VARCHAR(120) NULL,
  `question_reqinreg` TINYINT NULL DEFAULT 0,
  `question_reqinasses` TINYINT NULL DEFAULT 0,
  `question_optperprj` TINYINT NULL DEFAULT 0,
  `parent_question` INT NULL,
  `user_name` VARCHAR(80) NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_question_user1_idx` (`user_name` ASC),
  INDEX `fk_question_question1_idx` (`parent_question` ASC),
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`user_name`)
    REFERENCES `climmobv3`.`user` (`user_name`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_question1`
    FOREIGN KEY (`parent_question`)
    REFERENCES `climmobv3`.`question` (`question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`qstoption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`qstoption` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`qstoption` (
  `question_id` INT NOT NULL,
  `value_code` INT NOT NULL,
  `value_desc` VARCHAR(120) NULL,
  PRIMARY KEY (`question_id`, `value_code`),
  CONSTRAINT `fk_qstoption_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `climmobv3`.`question` (`question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`technology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`technology` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`technology` (
  `tech_id` INT NOT NULL AUTO_INCREMENT,
  `tech_name` VARCHAR(45) NULL,
  `user_name` VARCHAR(80) NULL,
  PRIMARY KEY (`tech_id`),
  INDEX `fk_crop_user1_idx` (`user_name` ASC),
  CONSTRAINT `fk_crop_user1`
    FOREIGN KEY (`user_name`)
    REFERENCES `climmobv3`.`user` (`user_name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`techalias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`techalias` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`techalias` (
  `tech_id` INT NOT NULL,
  `alias_id` INT NOT NULL,
  `alias_name` VARCHAR(120) NULL,
  PRIMARY KEY (`tech_id`, `alias_id`),
  INDEX `fk_techalias_technology1_idx` (`tech_id` ASC),
  CONSTRAINT `fk_techalias_technology1`
    FOREIGN KEY (`tech_id`)
    REFERENCES `climmobv3`.`technology` (`tech_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjtech`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjtech` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjtech` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `tech_id` INT NOT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `tech_id`),
  INDEX `fk_prjtech_technology1_idx` (`tech_id` ASC),
  CONSTRAINT `fk_prjtech_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prjtech_technology1`
    FOREIGN KEY (`tech_id`)
    REFERENCES `climmobv3`.`technology` (`tech_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjalias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjalias` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjalias` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `tech_id` INT NOT NULL,
  `alias_id` INT NOT NULL,
  `alias_name` VARCHAR(120) NULL,
  `tech_used` INT NOT NULL,
  `alias_used` INT NOT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `tech_id`, `alias_id`),
  INDEX `fk_prjalias_prjtech1_idx` (`user_name` ASC, `project_cod` ASC, `tech_id` ASC),
  INDEX `fk_prjalias_techalias1_idx` (`tech_used` ASC, `alias_used` ASC),
  CONSTRAINT `fk_prjalias_prjtech1`
    FOREIGN KEY (`user_name` , `project_cod` , `tech_id`)
    REFERENCES `climmobv3`.`prjtech` (`user_name` , `project_cod` , `tech_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prjalias_techalias1`
    FOREIGN KEY (`tech_used` , `alias_used`)
    REFERENCES `climmobv3`.`techalias` (`tech_id` , `alias_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`package` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`package` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `package_id` INT NOT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `package_id`),
  CONSTRAINT `fk_package_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`submission` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`submission` (
  `submission_uuid` VARCHAR(80) NOT NULL,
  `submission_date` DATETIME NULL,
  `submission_type` INT NULL COMMENT 'Can be registry or assessment\n',
  PRIMARY KEY (`submission_uuid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`regsection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`regsection` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`regsection` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `section_id` INT NOT NULL,
  `section_name` VARCHAR(45) NULL,
  `section_content` TEXT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `section_id`),
  CONSTRAINT `fk_regsection_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Registry section / Seccion en registro';


-- -----------------------------------------------------
-- Table `climmobv3`.`registry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`registry` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`registry` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `question_id` INT NOT NULL,
  `section_user` VARCHAR(80) NULL,
  `section_project` VARCHAR(80) NULL,
  `section_id` INT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `question_id`),
  INDEX `fk_registry_question1_idx` (`question_id` ASC),
  INDEX `fk_registry_regsection1_idx` (`section_user` ASC, `section_project` ASC, `section_id` ASC),
  CONSTRAINT `fk_registry_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registry_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `climmobv3`.`question` (`question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registry_regsection1`
    FOREIGN KEY (`section_user` , `section_project` , `section_id`)
    REFERENCES `climmobv3`.`regsection` (`user_name` , `project_cod` , `section_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`qstprjopt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`qstprjopt` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`qstprjopt` (
  `project_user` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `question_id` INT NOT NULL,
  `value_code` INT NOT NULL,
  `value_desc` VARCHAR(120) NULL,
  `parent_user` VARCHAR(80) NULL,
  `parent_project` VARCHAR(80) NULL,
  `parent_question` INT NULL,
  `parent_value` INT NULL,
  PRIMARY KEY (`project_user`, `project_cod`, `question_id`, `value_code`),
  INDEX `fk_qstprjopt_question1_idx` (`question_id` ASC),
  INDEX `fk_qstprjopt_qstprjopt1_idx` (`parent_user` ASC, `parent_project` ASC, `parent_question` ASC, `parent_value` ASC),
  CONSTRAINT `fk_qstprjopt_project1`
    FOREIGN KEY (`project_user` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qstprjopt_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `climmobv3`.`question` (`question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qstprjopt_qstprjopt1`
    FOREIGN KEY (`parent_user` , `parent_project` , `parent_question` , `parent_value`)
    REFERENCES `climmobv3`.`qstprjopt` (`project_user` , `project_cod` , `question_id` , `value_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`registryresp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`registryresp` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`registryresp` (
  `submission_uuid` VARCHAR(80) NOT NULL,
  `resp_uuid` VARCHAR(80) NOT NULL,
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `question_id` INT NOT NULL,
  `resp_intvalue` INT NULL,
  `resp_decvalue` DECIMAL(11,3) NULL,
  `resp_datevalue` DATETIME NULL,
  `resp_txtvalue` TEXT NULL,
  `resp_question` INT NULL,
  `resp_value` INT NULL,
  `qstprjopt_user` VARCHAR(80) NULL,
  `qstprjopt_project` VARCHAR(80) NULL,
  `qstprjopt_question` INT NULL,
  `qstprjopt_value` INT NULL,
  PRIMARY KEY (`submission_uuid`, `resp_uuid`),
  INDEX `fk_response_qstoption1_idx` (`resp_question` ASC, `resp_value` ASC),
  INDEX `fk_response_submission1_idx` (`submission_uuid` ASC),
  INDEX `fk_registryresp_registry1_idx` (`user_name` ASC, `project_cod` ASC, `question_id` ASC),
  INDEX `fk_registryresp_qstprjopt1_idx` (`qstprjopt_user` ASC, `qstprjopt_project` ASC, `qstprjopt_question` ASC, `qstprjopt_value` ASC),
  CONSTRAINT `fk_response_qstoption1`
    FOREIGN KEY (`resp_question` , `resp_value`)
    REFERENCES `climmobv3`.`qstoption` (`question_id` , `value_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_response_submission1`
    FOREIGN KEY (`submission_uuid`)
    REFERENCES `climmobv3`.`submission` (`submission_uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registryresp_registry1`
    FOREIGN KEY (`user_name` , `project_cod` , `question_id`)
    REFERENCES `climmobv3`.`registry` (`user_name` , `project_cod` , `question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registryresp_qstprjopt1`
    FOREIGN KEY (`qstprjopt_user` , `qstprjopt_project` , `qstprjopt_question` , `qstprjopt_value`)
    REFERENCES `climmobv3`.`qstprjopt` (`project_user` , `project_cod` , `question_id` , `value_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`i18n`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`i18n` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`i18n` (
  `lang_code` VARCHAR(5) NOT NULL,
  `lang_name` VARCHAR(120) NULL,
  PRIMARY KEY (`lang_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`enumerator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`enumerator` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`enumerator` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `enum_id` VARCHAR(80) NOT NULL,
  `enum_name` VARCHAR(120) NULL,
  `enum_password` VARCHAR(80) NULL,
  `enum_active` TINYINT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `enum_id`),
  CONSTRAINT `fk_enumerator_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjcombination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjcombination` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjcombination` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `comb_code` INT NOT NULL,
  `comb_usable` TINYINT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `comb_code`),
  CONSTRAINT `fk_prjcombination_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjcombdet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjcombdet` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjcombdet` (
  `prjcomb_user` VARCHAR(80) NOT NULL,
  `prjcomb_project` VARCHAR(80) NOT NULL,
  `comb_code` INT NOT NULL,
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `tech_id` INT NOT NULL,
  `alias_id` INT NOT NULL,
  PRIMARY KEY (`prjcomb_user`, `prjcomb_project`, `comb_code`, `user_name`, `project_cod`, `tech_id`, `alias_id`),
  INDEX `fk_prjcombdet_prjalias1_idx` (`user_name` ASC, `project_cod` ASC, `tech_id` ASC, `alias_id` ASC),
  CONSTRAINT `fk_prjcombdet_prjcombination1`
    FOREIGN KEY (`prjcomb_user` , `prjcomb_project` , `comb_code`)
    REFERENCES `climmobv3`.`prjcombination` (`user_name` , `project_cod` , `comb_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prjcombdet_prjalias1`
    FOREIGN KEY (`user_name` , `project_cod` , `tech_id` , `alias_id`)
    REFERENCES `climmobv3`.`prjalias` (`user_name` , `project_cod` , `tech_id` , `alias_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`pkgcomb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`pkgcomb` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`pkgcomb` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `package_id` INT NOT NULL,
  `comb_user` VARCHAR(80) NOT NULL,
  `comb_project` VARCHAR(80) NOT NULL,
  `comb_code` INT NOT NULL,
  `pkgcomb_code` VARCHAR(45) NULL,
  `pkgcomb_image` BLOB NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `package_id`, `comb_user`, `comb_project`, `comb_code`),
  INDEX `fk_pkgcomb_prjcombination1_idx` (`comb_user` ASC, `comb_project` ASC, `comb_code` ASC),
  CONSTRAINT `fk_pkgcomb_package1`
    FOREIGN KEY (`user_name` , `project_cod` , `package_id`)
    REFERENCES `climmobv3`.`package` (`user_name` , `project_cod` , `package_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pkgcomb_prjcombination1`
    FOREIGN KEY (`comb_user` , `comb_project` , `comb_code`)
    REFERENCES `climmobv3`.`prjcombination` (`user_name` , `project_cod` , `comb_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`asssection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`asssection` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`asssection` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `section_id` INT NOT NULL,
  `section_name` VARCHAR(120) NULL,
  `section_content` TEXT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `section_id`),
  CONSTRAINT `fk_asssection_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`assessment` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`assessment` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `question_id` INT NOT NULL,
  `section_user` VARCHAR(80) NOT NULL,
  `section_project` VARCHAR(80) NOT NULL,
  `section_id` INT NOT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `question_id`),
  INDEX `fk_assessment_question1_idx` (`question_id` ASC),
  INDEX `fk_assessment_asssection1_idx` (`section_user` ASC, `section_project` ASC, `section_id` ASC),
  CONSTRAINT `fk_assessment_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assessment_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `climmobv3`.`question` (`question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assessment_asssection1`
    FOREIGN KEY (`section_user` , `section_project` , `section_id`)
    REFERENCES `climmobv3`.`asssection` (`user_name` , `project_cod` , `section_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`assresp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`assresp` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`assresp` (
  `submission_uuid` VARCHAR(80) NOT NULL,
  `resp_uuid` VARCHAR(80) NOT NULL,
  `ass_user` VARCHAR(80) NOT NULL,
  `ass_project` VARCHAR(80) NOT NULL,
  `ass_question` INT NOT NULL,
  `resp_intvalue` INT NULL,
  `resp_decvalue` DECIMAL(11,3) NULL,
  `resp_datevalue` DATETIME NULL,
  `resp_txtvalue` TEXT NULL,
  `resp_question` INT NULL,
  `resp_value` INT NULL,
  `qstprjopt_user` VARCHAR(80) NULL,
  `qstprjopt_project` VARCHAR(80) NULL,
  `qstprjopt_question` INT NULL,
  `qstprjopt_value` INT NULL,
  PRIMARY KEY (`submission_uuid`, `resp_uuid`),
  INDEX `fk_response_qstoption1_idx` (`resp_question` ASC, `resp_value` ASC),
  INDEX `fk_assresp_submission1_idx` (`submission_uuid` ASC),
  INDEX `fk_assresp_qstprjopt1_idx` (`qstprjopt_user` ASC, `qstprjopt_project` ASC, `qstprjopt_question` ASC, `qstprjopt_value` ASC),
  INDEX `fk_assresp_assessment1_idx` (`ass_user` ASC, `ass_project` ASC, `ass_question` ASC),
  CONSTRAINT `fk_assresp_qstoption1`
    FOREIGN KEY (`resp_question` , `resp_value`)
    REFERENCES `climmobv3`.`qstoption` (`question_id` , `value_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assresp_submission1`
    FOREIGN KEY (`submission_uuid`)
    REFERENCES `climmobv3`.`submission` (`submission_uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assresp_qstprjopt1`
    FOREIGN KEY (`qstprjopt_user` , `qstprjopt_project` , `qstprjopt_question` , `qstprjopt_value`)
    REFERENCES `climmobv3`.`qstprjopt` (`project_user` , `project_cod` , `question_id` , `value_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assresp_assessment1`
    FOREIGN KEY (`ass_user` , `ass_project` , `ass_question`)
    REFERENCES `climmobv3`.`assessment` (`user_name` , `project_cod` , `question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjcnty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjcnty` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjcnty` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `cnty_cod` VARCHAR(3) NOT NULL,
  `cnty_contact` VARCHAR(120) NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `cnty_cod`),
  INDEX `fk_prjcnty_country1_idx` (`cnty_cod` ASC),
  CONSTRAINT `fk_prjcnty_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prjcnty_country1`
    FOREIGN KEY (`cnty_cod`)
    REFERENCES `climmobv3`.`country` (`cnty_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjlang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjlang` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjlang` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `lang_code` VARCHAR(5) NOT NULL,
  `lang_default` TINYINT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `lang_code`),
  INDEX `fk_prjlang_i18n1_idx` (`lang_code` ASC),
  CONSTRAINT `fk_prjlang_project1`
    FOREIGN KEY (`user_name` , `project_cod`)
    REFERENCES `climmobv3`.`project` (`user_name` , `project_cod`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prjlang_i18n1`
    FOREIGN KEY (`lang_code`)
    REFERENCES `climmobv3`.`i18n` (`lang_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
