-- MySQL Script generated by MySQL Workbench
-- Thu 28 Apr 2016 17:27:09 EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema climmobv3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `climmobv3` ;

-- -----------------------------------------------------
-- Schema climmobv3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `climmobv3` DEFAULT CHARACTER SET utf8 ;
USE `climmobv3` ;

-- -----------------------------------------------------
-- Table `climmobv3`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`country` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`country` (
  `cnty_cod` VARCHAR(3) NOT NULL,
  `cnty_name` VARCHAR(120) NULL,
  PRIMARY KEY (`cnty_cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`sector` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`sector` (
  `sector_cod` INT NOT NULL AUTO_INCREMENT,
  `sector_name` VARCHAR(120) NULL,
  PRIMARY KEY (`sector_cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`user` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`user` (
  `user_name` VARCHAR(80) NOT NULL,
  `user_fullname` VARCHAR(120) NULL,
  `user_password` VARCHAR(80) NULL,
  `user_organization` VARCHAR(120) NULL,
  `user_email` VARCHAR(120) NULL,
  `user_apikey` VARCHAR(45) NULL,
  `user_about` TEXT NULL,
  `user_cnty` VARCHAR(3) NOT NULL,
  `user_sector` INT NOT NULL,
  `user_active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`user_name`),
  INDEX `fk_user_lkpcountry_idx` (`user_cnty` ASC),
  INDEX `fk_user_lkpsector1_idx` (`user_sector` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`activitylog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`activitylog` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`activitylog` (
  `log_id` INT(9) NOT NULL AUTO_INCREMENT,
  `log_user` VARCHAR(80) NOT NULL,
  `log_datetime` DATETIME NULL,
  `log_type` VARCHAR(3) NULL,
  `log_message` TEXT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_activitylog_user1_idx` (`log_user` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`apilog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`apilog` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`apilog` (
  `log_id` INT(9) NOT NULL AUTO_INCREMENT,
  `log_datetime` DATETIME NULL,
  `log_ip` VARCHAR(45) NULL,
  `log_user` VARCHAR(80) NOT NULL,
  `log_uuid` VARCHAR(80) NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_apilog_user1_idx` (`log_user` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`crop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`crop` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`crop` (
  `crop_id` INT NOT NULL AUTO_INCREMENT,
  `crop_name` VARCHAR(45) NULL,
  `user_name` VARCHAR(80) NULL,
  PRIMARY KEY (`crop_id`),
  INDEX `fk_crop_user1_idx` (`user_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`i18n`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`i18n` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`i18n` (
  `lang_code` VARCHAR(5) NOT NULL,
  `lang_name` VARCHAR(120) NULL,
  PRIMARY KEY (`lang_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`project` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`project` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `project_name` VARCHAR(120) NULL,
  `project_abstract` TEXT NULL,
  `project_tags` TEXT NULL,
  `project_pi` VARCHAR(120) NULL,
  `project_piemail` VARCHAR(120) NULL,
  `project_cnty` VARCHAR(3) NOT NULL,
  `project_crop` INT NOT NULL,
  `project_lang` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`user_name`, `project_cod`),
  INDEX `fk_project_lkpcountry1_idx` (`project_cnty` ASC),
  INDEX `fk_project_user1_idx` (`user_name` ASC),
  INDEX `fk_project_crop1_idx` (`project_crop` ASC),
  INDEX `fk_project_i18n1_idx` (`project_lang` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`question` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question_desc` VARCHAR(120) NULL,
  `question_notes` TEXT NULL,
  `question_unit` VARCHAR(120) NULL,
  `question_type` INT NULL,
  `question_dtype` INT NULL,
  `user_name` VARCHAR(80) NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_question_user1_idx` (`user_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`qstoption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`qstoption` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`qstoption` (
  `question_id` INT NOT NULL,
  `value_code` INT NOT NULL,
  `value_desc` VARCHAR(120) NULL,
  PRIMARY KEY (`question_id`, `value_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjquestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjquestion` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjquestion` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `question_id` INT NOT NULL,
  `added_date` DATETIME NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `question_id`),
  INDEX `fk_projectquestion_question1_idx` (`question_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`variety`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`variety` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`variety` (
  `crop_id` INT NOT NULL,
  `variety_id` INT NOT NULL,
  `variety_name` VARCHAR(120) NULL,
  PRIMARY KEY (`crop_id`, `variety_id`),
  INDEX `fk_variety_crop1_idx` (`crop_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`prjvariety`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`prjvariety` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`prjvariety` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `variety_id` INT NOT NULL,
  `variety_name` VARCHAR(120) NULL,
  `source_crop` INT NULL,
  `source_variety` INT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `variety_id`),
  INDEX `fk_prjvariety_variety1_idx` (`source_crop` ASC, `source_variety` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`package` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`package` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `package_id` INT NOT NULL,
  `varietya_user` VARCHAR(80) NOT NULL,
  `varietya_project` VARCHAR(80) NOT NULL,
  `varietya_variety` INT NOT NULL,
  `varietyb_user` VARCHAR(80) NOT NULL,
  `varietyb_project` VARCHAR(80) NOT NULL,
  `varietyb_variety` INT NOT NULL,
  `varietyc_user` VARCHAR(80) NOT NULL,
  `varietyc_project` VARCHAR(80) NOT NULL,
  `varietyc_variety` INT NOT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `package_id`),
  INDEX `fk_package_prjvariety1_idx` (`varietya_user` ASC, `varietya_project` ASC, `varietya_variety` ASC),
  INDEX `fk_package_prjvariety2_idx` (`varietyb_user` ASC, `varietyb_project` ASC, `varietyb_variety` ASC),
  INDEX `fk_package_prjvariety3_idx` (`varietyc_user` ASC, `varietyc_project` ASC, `varietyc_variety` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`enumerator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`enumerator` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`enumerator` (
  `user_name` VARCHAR(80) NOT NULL,
  `project_cod` VARCHAR(80) NOT NULL,
  `enum_id` VARCHAR(80) NOT NULL,
  `enum_name` VARCHAR(120) NULL,
  `enum_password` VARCHAR(80) NULL,
  `enum_active` TINYINT NULL,
  PRIMARY KEY (`user_name`, `project_cod`, `enum_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climmobv3`.`submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`submission` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`submission` (
  `submission_uuid` VARCHAR(80) NOT NULL,
  `submission_date` DATETIME NULL,
  `submission_source` VARCHAR(45) NULL,
  `submission_sourceuuid` VARCHAR(80) NULL,
  `enum_user` VARCHAR(80) NOT NULL,
  `enum_project` VARCHAR(80) NOT NULL,
  `enum_id` VARCHAR(80) NOT NULL,
  `package_user` VARCHAR(80) NOT NULL,
  `package_project` VARCHAR(80) NOT NULL,
  `package_id` INT NOT NULL,
  PRIMARY KEY (`submission_uuid`),
  INDEX `fk_submission_enumerator1_idx` (`enum_user` ASC, `enum_project` ASC, `enum_id` ASC),
  INDEX `fk_submission_package1_idx` (`package_user` ASC, `package_project` ASC, `package_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `climmobv3`.`response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climmobv3`.`response` ;

CREATE TABLE IF NOT EXISTS `climmobv3`.`response` (
  `submission_uuid` VARCHAR(80) NOT NULL,
  `resp_uuid` VARCHAR(80) NOT NULL,
  `prjuser_name` VARCHAR(80) NOT NULL,
  `prjproject_cod` VARCHAR(80) NOT NULL,
  `question_id` INT NOT NULL,
  `resp_intvalue` INT NULL,
  `resp_decvalue` DECIMAL(11,3) NULL,
  `resp_datevalue` DATETIME NULL,
  `resp_txtvalue` TEXT NULL,
  `resp_question` INT NULL,
  `resp_value` INT NULL,
  `resp_variety_user` VARCHAR(80) NULL,
  `resp_variety_project` VARCHAR(80) NULL,
  `resp_variety_id` INT NULL,
  PRIMARY KEY (`submission_uuid`, `resp_uuid`),
  INDEX `fk_response_projectquestion1_idx` (`prjuser_name` ASC, `prjproject_cod` ASC, `question_id` ASC),
  INDEX `fk_response_qstoption1_idx` (`resp_question` ASC, `resp_value` ASC),
  INDEX `fk_response_prjvariety1_idx` (`resp_variety_user` ASC, `resp_variety_project` ASC, `resp_variety_id` ASC),
  INDEX `fk_response_submission1_idx` (`submission_uuid` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
